import './main.scss';

import GridDebugger from '@Layout/GridDebugger';
import type { Metadata } from 'next';

import { inter } from './fonts';
import GSAP from '@Layout/Gsap';
import Layout from '@Layout/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Layout>{children}</Layout>
        <GridDebugger />
        <GSAP />
      </body>
    </html>
  );
}
